name: money_to_text
description: It converts any double variable you send with this dart package to text as money
version: 1.0.2
homepage: https://github.com/avdisx
repository: https://github.com/avdisx/money_to_text
documentation: https://github.com/avdisx/money_to_text

environment:
  sdk: ">=2.18.6 <3.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.1
  test: ^1.23.1
