name: money_to_text
description: It converts any double variable you send with this dart package to text as money
version: 1.0.4
homepage: https://github.com/ahmetveysels
repository: https://github.com/ahmetveysels/money_to_text
documentation: https://github.com/ahmetveysels/money_to_text

environment:
  sdk: '>=3.2.3 <4.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.0
 